kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 64vgXORL+59r0YTYlmNAmDBUPZkjqHzntW6AXNlGzro=
      - identity: {}
